### ISSUE TITLE
Multiple weaves shorter than 0.6

### ISSUE THREAD

**Issue by Nikolizzer** [Soreepeong/XivAlexander#10]
![weaves](https://user-images.githubusercontent.com/79022493/107859659-91a05480-6e43-11eb-8093-3f97f962c9ad.png)

I've been using the tool and in encounter logs I've found anomalies like this way too frequently. This is on a version I downloaded on the 12th and I play at around 50 to 55ms.

**Comment by Soreepeong** [comment]
What does the second column indicate? Since this program will make *outgoing* requests from the client's interval become no lesser than 675ms for short actions, while ACT parses from *incoming* responses from the server, parse result's action interval may look inconsistent, but it's working as intended if it's above 675ms when averaged.

Other than that, there was an issue which happened because I failed to consider auto attacks. Can you try with the newest release again, and attach log from XivAlexander? You can check out logs by using "Show Logging Window" from program's tray menu.

**Comment by godonlyknowswho** [comment]
Hey, new person here, saw this and was a bit worried so I tried to recreate and sure enough:
![weaves](https://user-images.githubusercontent.com/79341225/108574146-aa8c9680-736a-11eb-99ee-3c00ce2deb9a.png)
The difference between 14.575 and 15.107 is only 0.532. 
This was done on the v1.12 version of XivAlexander. I have quite high ping, around ~180 ms.

While there's only one instance I can find in this log, I've seen it come up a bunch in other logs. It's inconsistent, if you really desperately needed it I could probably get the same info with more examples over a longer period of time, but it'd be a nuisance. I don't know if this will help, but I notice that it seems to be the animation lock of weapon skills that is the issue, I've never caught an oGCD skill being below 0.6 seconds.

Here's the log from XivAlexander during this period:
[alexanderlog.txt](https://github.com/Soreepeong/XivAlexander/files/6013724/alexanderlog.txt)

**Comment by Harxen** [comment]
Were there any updates on this? Just curious if it was fixed

**Comment by Soreepeong** [comment]
I don't think this is a problem, as it also can happen on sufficiently low ping, since ACT logs are generated from server response, and server timers can fluctuate from client timers.
