### ISSUE TITLE
EXDF Translations break /ac Macros

### ISSUE THREAD

**Issue by SashaFFXIV** [Soreepeong/XivAlexander#183]

**Comment by SashaFFXIV** [comment]
Bandaid fix is to remove Actions, PetActions, and CraftActions from the json file. You can also remove Status to fix /statusoff macros.

**Comment by Soreepeong** [comment]
You can also use auto-translate functions so that your macros work regardless of which language you play the game in.

Try typing `/ac cu` and press `Tab` key, and you'll get a list of completion items. If you pick one from those, then it will work regardless of game language or whether you use EXDF transformation rules feature. Same goes for `/statusoff`.

The only two occurrences that I can think of where you can't use this is when you're using `<recast.actionname>` placeholder or using `/quickchat "Nice job"`, where the former does not support auto-translate feature and the latter does not have an auto-translate dictionary item for some reason.

**Comment by SashaFFXIV** [comment]
I had no idea you could use auto translates in macros. Thanks!
