### ISSUE TITLE
Modding Questions

### ISSUE THREAD

**Issue by opengrip** [Soreepeong/XivAlexander#221]
Hey I have a few questions that I can't seem to confirm for myself concerning the modding feature. I only started using this at the start of EW so I know its bad timing since things could be broken either way and restarting to log in is a pain to test things. I've installed some mods and I know some are working for sure since the maps are definitely changed using the moogle maps mod. This being said I noticed some mods have a lot of options in the menu. For example Hair Defined says the main mod is enabled but each race and gender has more options that aren't clicked on by default. Do these all need to be turned on to be working? Also are things supposed to change in real time? If I turn off or on a mod will it change the texture in game right away or does it need a restart? Thanks for the help in advance. 
![Capture](https://user-images.githubusercontent.com/95540448/144717412-193d4aeb-ff1c-4b2d-ab06-e7ea89dcee3d.PNG)

**Comment by Soreepeong** [comment]
If a mod requires game restart to take effect, it will be displayed that game needs to be restarted inside individual mod menu. For the menu in the screencap, it should not require restart, but if said body part of that particular race has been loaded by the game already (because you have logged in and someone have walked by whose character customization is affected by the mods you're using), then the character might look "wrong" until you restart the game. Else than that, changes in mod choices will be applied on next character reload (gear change, zone change, etc.)

Also, you will have to choose the ones you'll use. From the looks of it, that modpack would support multiple choices per mod option - modding both male and female hairs for Midlanders. For now, you can just choose both, and if it keeps reverting to selecting only one, try holding Ctrl or Shift while selecting another.

**Comment by opengrip** [comment]
Gotcha so I need to go through and select everything manually. Thanks
