### ISSUE TITLE
Unexpected Error: Cannot find path specified while trying to install

### ISSUE THREAD

**Issue by farronheichou** [Soreepeong/XivAlexander#259]
I noticed xivalexander didn't open today with XIVLauncher so I decided to uninstall it and reinstall. When trying to reinstall I get this error. No mods installed other than XIVLauncher and its corresponding plugins.

**Comment by farronheichou** [comment]
![image](https://user-images.githubusercontent.com/76195992/147567218-4df4c135-2543-4f02-b3df-09d96072328e.png)

**Comment by Oglaf** [comment]
I thought this was a corrupted installation problem and did a fresh installation without XIVLauncher and GShader because I was getting many DirectX fatal errors.

It looks like SquareEnix has changed their folder structure:
![image](https://user-images.githubusercontent.com/31038423/147571086-3515428c-1955-4bca-ad4b-1345f4023d9c.png)

@Soreepeong, d3d11.dll has been renamed to XInputXIV3.dll

**Comment by farronheichou** [comment]
It seems to have worked for me after doing a fresh installation of everything. This is how the folder looks to me

![image](https://user-images.githubusercontent.com/76195992/147572182-0bf16e39-b724-4bf1-ad96-13c048e704d2.png)

**Comment by Oglaf** [comment]
I did another fresh install through Steam and repaired files through FFXIV Launcher, launched the game "normally" and using XIVLauncher. Still no DirectX DLL.

I opened the game on my notebook and I noticed after an update the DLLs were gone.

Could you zip d3d11.dll and share with me?

**Comment by Soreepeong** [comment]
Pressing "Install" button from loader will copy the files to game folder. Make sure to install when the game is not running.

**Comment by Oglaf** [comment]
Selecting "Instal XivAlexander as d3d9 and d3d11" gave me the error above.

**Comment by Soreepeong** [comment]
Are you using any antivirus software? Try adding to exceptions, then restart, then try again.

**Comment by Oglaf** [comment]
No anti-virus, using Windows 11 v22000.376, disabled real-time protection. Same problem.

**Comment by Soreepeong** [comment]
1. Does your Windows username contain any non-ASCII character? I think I fixed it, but it might still be tripping, so just in case.
    ![ASCII Table](https://www.asciitable.com/asciifull.gif)
2. Did you extract all files first from the zip download from Release page, and then ran Loader?
    * You cannot have reached that messagebox to begin with if this was the case, but still.
3. Did your latest install error message happen when you haven't even installed GShade yet?
    * That error message does not make sense if you did extract all files from release zip first and the game installation does exist at that path (minus d3d11.dll). GShade placing a file link on GShade install might be a culprit, especially if you removed GShade but for some reason it did not remove the file link automatically.
    * If `d3d11.dll` remains after removing GShade, remove it manually, and try installing XivAlexander again.

For `d3d11.dll` placed by XivAlexander install, it's simply nothing more than a copy of `XivAlexander64.dll`. You can refer to [Installation and Load Once](https://github.com/Soreepeong/XivAlexander/wiki/Installation-and-Load-Once#manual-installation) if you'd like to try setting it up yourself.

**Comment by Oglaf** [comment]
1. No, my windows username is chris, that shouldn't be a problem.
2. Yes, I downloaded the lasted release and unzipped using 7zip and ran load as administrator.
3. I haven't touched GShade since I have deleted and re-downloaded the game to confirm if game crash is related to XIVAlexander or any other mod/gshade.

I do have FF14 installed on a custom path, but the loader is able to detected it:
![image](https://user-images.githubusercontent.com/31038423/147721458-720a796a-29e4-4991-8651-4f1a1256a15c.png)

To be honest, I am testing NoClippy as an alternative and I am not in a rush to solve it manually. I have seen another Issue was raised about the same problem (#222). I will not touch modding or GShade right now to keep the "Bug Scenario" untouched if you desire to keep investigating.

Is it possible to add an exception if renaming and pasting XivAlexander64.dll fails?
