### ISSUE TITLE
Direct X error (11000002)

### ISSUE THREAD

**Issue by oonly2645** [Soreepeong/XivAlexander#269]
After I started using xivalexander, I have been getting intermitent crashes due to this error. I crash like everytime I start up the game and a couple time throughout the day. Not sure what is causing it. Attached is some of the logs I exported after the crash. Sometimes it even causes my monitors to go black and I have to restart my pc.
[XivAlexander_20211231_112011_606.log](https://github.com/Soreepeong/XivAlexander/files/7795259/XivAlexander_20211231_112011_606.log)
[XivAlexander_20211230_131021_905.log](https://github.com/Soreepeong/XivAlexander/files/7795260/XivAlexander_20211230_131021_905.log)
[XivAlexander_20211228_115057_494.log](https://github.com/Soreepeong/XivAlexander/files/7795261/XivAlexander_20211228_115057_494.log)

**Comment by Soreepeong** [comment]
XivAlexander cannot cause DirectX errors, minus for the cases of corrupted TexTools ModPack files being used or paritially corrupt game installation.

* Just in case, can you do integrity check from FFXIVQuickLauncher? If you ever used TexTools, there is above zero chance you updated the game without disabling mods, so just making sure.
* If you have Modding enabled from XivAlexander, try disabling it and see if it doesnt crash anymore.
* See if running XivAlexander with Dalamud solves it. If it does, share me the list of plugins you have installed (possibly including Dalamud logs), to see if anything conflicts with XivAlexander.

Also, try going to The Waking Sands so that nobody else is there, and see if you won't crash as long as you remain there. It'd be best if you can discern doing what exactly in the game makes the game crash - like, for example, "when the game is about to play FATE background music".

**Comment by justin767** [comment]
> After I started using xivalexander, I have been getting intermitent crashes due to this error. I crash like everytime I start up the game and a couple time throughout the day. Not sure what is causing it. Attached is some of the logs I exported after the crash. Sometimes it even causes my monitors to go black and I have to restart my pc. [XivAlexander_20211231_112011_606.log](https://github.com/Soreepeong/XivAlexander/files/7795259/XivAlexander_20211231_112011_606.log) [XivAlexander_20211230_131021_905.log](https://github.com/Soreepeong/XivAlexander/files/7795260/XivAlexander_20211230_131021_905.log) [XivAlexander_20211228_115057_494.log](https://github.com/Soreepeong/XivAlexander/files/7795261/XivAlexander_20211228_115057_494.log)

I'm experiencing the exact same issue, were you able to solve this?

**Comment by oonly2645** [comment]
It was fine for like a few days after I did an integrity check but it suddenly crash again today when I was in front of a marketboard in Shirongane housing district with no one around me selling stuff on my retainer. I attached both the alexander log and the dalamud log that contents all the plugins that i am using. 
[XivAlexander_20220104_115943_520.log](https://github.com/Soreepeong/XivAlexander/files/7805276/XivAlexander_20220104_115943_520.log)
[dalamud.log](https://github.com/Soreepeong/XivAlexander/files/7805277/dalamud.log)

**Comment by Soreepeong** [comment]
I would start troubleshooting by disabling Market Board plugin and PriceCheck, as those are most related to the problem trigger you have experienced.
