### ISSUE TITLE
Can't get to the load screen.

### ISSUE THREAD

**Issue by ffxivcoding** [Soreepeong/XivAlexander#274]
After I press install on the xivalexander window, it just reverts back to the [same instalation window](https://github.com/Soreepeong/XivAlexander/raw/wiki-resources/installation/loader-install.png?raw=true) instead of the [load window](https://github.com/Soreepeong/XivAlexander/raw/wiki-resources/installation/loader-loadonce.png?raw=true) that I hear so much about but never actually saw it, because everytime I try installing it (tried all installation options) this happens.

Regardless, it says "Installed: International" so I try launching the game.
I can see [this](https://i.ibb.co/DpZyFzn/1.png) and [this](https://i.ibb.co/d7wwGZy/2PNG.png) so apparently, even though I can't access the load window for some forsaken reason, it appears to be working. But my oGCDs still clip A LOT, and I've used XivAlexander for almost all year and I'm sure something is not right.

Is my installation ok? Should I do something different?

Additional Information:
- I use XIV Launcher and placed a command on the property tab on steam to allow me start the game through the launcher: "C:\Users\MyUserName\AppData\Local\XIVLauncher\XIVLauncher.exe" %command%
- I'm running everything with admin permissions.
- Placed a Firewall Exception on everything related to this.
- Reinstalled everything multiple times.

**Comment by Soreepeong** [comment]
Does no messagebox indicating it's installed shows up after pressing install button? And, for load window, you have to press on the last option AFTER running the game and refreshing. "Load once" only shows up when the game is running.

Are you using VPNs? Are you using Mudfish with FastConnect on? You might want to turn that off. If your VPN is a shoddy one, you might want to try out `Networking > Troubleshooting > Take Over <anything>`. Otherwise, try fiddling with `Networking > High Latency Mitigation > Mode 1/2/3` and see if anything works.

Open up log window, and try using any actions. If stuff get printed out when you use actions, then it's working; otherwise, more troubleshooting will be required.

**Comment by ffxivcoding** [comment]
I see, now I understand about the load window, thanks!
About the VPN, I'm running it with ExitLag. I'll experiment with the latency mitigation modes.

Are those 3 modes safe to use? I heard of some guy who got banned because he simulated a latency so low that got to the point where there was no animation at all.

Also, it's ok to change that while the game is open?

**Comment by Soreepeong** [comment]
They're probably fine, but you're up to your own with your best judgement.

**Comment by ffxivcoding** [comment]
Thank you much for all the info!
