### ISSUE TITLE
Control Window now displayed as FFXIV  window

### ISSUE THREAD

**Issue by tsmaddox15** [Soreepeong/XivAlexander#291]
After updating to 1.14.8.46 1.14.8.40 the control window that opens when alex is loaded in is showing as a window for ffxiv. Now if I wanted to unload the alex I'm unable to unless I exit the game.

![image](https://user-images.githubusercontent.com/17345835/148438203-bf17a576-d525-4195-bc25-100d8ee94612.png)

![image](https://user-images.githubusercontent.com/17345835/148438553-537d7028-f442-4d6e-85a5-79c8cdf4d269.png)

**Comment by DAOWAce** [comment]
Is that the cause for this?  I haven't been unable to unload Alexander since I updated to the versions that added mod support (to which I set it to use DINPUT8).

Don't know if it's because I use other things like XIVLauncher or GShade, as I'd rather not play the game without them.

**Comment by Soreepeong** [comment]
For unloading, when did you run XivAlexander? If you set it to run automatically from FFXIVQuickLauncher, it might have been loaded too early that something else - like Dalamud - has hooked upon it, preventing safe unload. 
If you installed XivAlexander, that is the expected behavior; you cannot unload this when installed, without unchecking "Use XivAlexander" from Restart menu.
