### ISSUE TITLE
high ping users can effectively lower their cast lock to 0.5-0.6s

### ISSUE THREAD

**Issue by anyoneminion** [Soreepeong/XivAlexander#3]
example with 200 ping https://i.imgur.com/qTGVR0e.png

this could be a massive problem for people in the 200-300 ms range, where they're going to be accused of using speeder or some cheat because their cast lock is lower than what's normally possible.

no this was not done by editing the source code, this is from the 1.01 release

**Comment by Soreepeong** [comment]
Thing is, when your connection effectively stalls for more than 500ms(server doesn't reply in 500ms), the client will release the animation lock, so unintentional double weaving has always beej possible as far as i know on high ping. This program would compensate for that by adding up the returned animation lock duration since the point of first request, and I've seen pretty good results from the current implementation, but if it isn't the case, can you copy and paste the log, which you can check out from **Show Logging Window** from tray menu?

**Comment by anyoneminion** [comment]
logs:
https://i.imgur.com/4o8Z3OY.png
https://i.imgur.com/50E71nx.png

fflogs showing 532 ms cast lock
https://i.imgur.com/vbAnzqZ.png

**Comment by Soreepeong** [comment]
Can you test again with this release: https://github.com/Soreepeong/XivAlexander/releases/tag/v1.02 

I just realized MCH's auto attack is 0x0008 instead of other jobs' 0x0007, so it might have been causing troubles calculating latency values. If it still lets you use actions too quickly, you can copy and paste the log window's text now, too!

**Comment by Soreepeong** [comment]
Try this: https://github.com/Soreepeong/XivAlexander/releases/tag/v1.03

Auto-attacks are now properly taken into consideration, preventing resets of animation locks.
