### ISSUE TITLE
Game crashes after exiting

### ISSUE THREAD

**Issue by Rajsen123** [Soreepeong/XivAlexander#318]
so i got xxivlauncher and xiv alexander. without xiv alexander the game works fine. i tried installin, tried to load once even tried to add xivalexander 64 to auto launch in xivlauncher but game always crashes after exiting. no error just not responding. have to force exit from task manager efverytime. pls help,

**Comment by Shizzz104** [comment]
I have somewhat similar (or the same?) issue. Just black screen when I press "Exit game".  It goes away if I click anywhere on it, otherwise it's there indefinitely it seems. The game is set to Borderless Windowed, fwiw.
Also it seems alexanders messes up Cactbot overlays. First my target bar was not loading, and today all of the overlays disappeared.
Removing alexander fixed both issues. 

I installed the previous version (v1.14.8.46 ), and overlays work again. Not sure if it is version specific, or just a result of reinstalling the add-on.
The black screen persists though.

**Comment by JakeG18** [comment]
I'm getting the issue as well with the black screen after clicking exit game. Usually if I click a few times or right click and close window on the task bar, it closes. But def seems like exit game is causing some kind of crash and a fix would be great.

**Comment by Soreepeong** [comment]
This should be fixed next release.

**Comment by JakeG18** [comment]
> This should be fixed next release.

awesome. love the plug-in btw. it's a life saver on the east coast. thanks for your hard work!!
