### ISSUE TITLE
Is it possible to use only ICMP ping for Mode 3?

### ISSUE THREAD

**Issue by amasover** [Soreepeong/XivAlexander#341]
Hello, I have a question/suggestion, though I'll admit my knowledge of network stuff is not fantastic. And thank you in advance for creating this awesome program!

I noticed that in Mode 3, XivAlexander is using the min of ICMP and TCP latency:

https://github.com/Soreepeong/XivAlexander/blob/c8fb321ce280eca9ca6d5ed25d8459540ce3c6e1/XivAlexander/Apps/MainApp/Internal/NetworkTimingHandler.cpp#L341

Problem is, some gaming VPNs are configured to send back TCP acks immediately (e.g., Mudfish Fastconnect mode):

![mudfishtcp](https://user-images.githubusercontent.com/484819/151871637-36287947-1c53-48f7-913d-ea10ae4850d3.PNG)

From Windows resource manager, FFXIV is showing TCP latency of 0ms.

However, at least with Mudfish, they no longer intercept ICMP requests (I think this is the change when that likely happened):

https://docs.mudfish.net/en/docs/mudfish-cloud-vpn/release-notes/#532-2021-01-20

So even with Mudfish Fastconnect mode running, ICMP RTT seems to be pretty accurate:

![icmpping](https://user-images.githubusercontent.com/484819/151872024-994324c8-9081-45d7-9387-9d3603d9480e.PNG)

Would it be possible for XivAlexander use only ICMP information for Mode 3, rather than the min of ICMP and TCP? And in that situation, would using a VPN/Proxy that immediately acks TCP requests cause issues?

**Comment by lilly-cm** [comment]
what would be the point of using ICMP pings if they going a different path than the game's actual traffic? I assume xiva uses the minimum trying to avoid being tricked by such split tunnels.

**Comment by karashiiro** [comment]
I can't say if it matters here since I'm not involved, but if the TCP ping is falsely being reported as 0 then it's effectively useless for ping tracking. ICMP ping may take a different route, but at least it's a real ping value. I'd either [take the maximum of the two or ignore one if there's too large of a disparity](https://github.com/karashiiro/PingPlugin/blob/b24f2f6980e4e9897bba4409b9a8b8cab3d41eb7/PingPlugin/PingTrackers/AggregatePingTracker.cs#L26-L46) (different ping algorithms but the same concept), but that's just me.

**Comment by Soreepeong** [comment]
@amasover I'll add an option that will let you decide which ping information to use:
1. min(ICMP, TCP) (Default)
2. ICMP, and then if unavailable, TCP

@lilly-cm @karashiiro ICMP pings are done using the same route with the game connection, by using the same source and destination IP addresses. Both ICMP and TCP latency information are used because TCP latency information tends to be higher than measured ICMP ping (actually <10ms but reported as 50ms, resulting in overmitigation), but ICMP is blocked on some network connections. In any case, maybe letting the users know easier that if ping measurement is incorrect or inconsistent they should try mode 2 which does not use measured data.

**Comment by lilly-cm** [comment]
I was specifically addressing what I think mudfish fastconnect is doing (proxying the tcp connections but not ICMP). i.e., application level split tunneling. In that case ICMP would be pretty useless I expect. Anyway more visibility is always appreciated, good plan!
