### ISSUE TITLE
alexander does not recognize I have an active license 

### ISSUE THREAD

**Issue by MyShep2** [Soreepeong/XivAlexander#356]
I'm playing on the steam version and I'm having the same error that would normally happen if I were to not have an active subscription. I payed my subscription a few days ago and have confirmed I can play the game running from the regular launcher. Something I'm missing?

**Comment by VilcsiTH** [comment]
Alexander uses the .dll file you wanted it to use on install, it has no "launcher", the "Run Game" option inside the installer just opens the regular launcher you mentioned using. The game will use Alexander as soon as its exe is running(by default, ffxiv_dx11.exe), because the game loads dlls inside the folder, which include Alexander. You can double-check if it's running by taking a look at the right side of your taskbar, there should be a tiny white cogwheel icon there while the game is open.
Are you sure you posted this issue to the correct place? I know, silly question, but it sounds like an [FFXIVQuickLauncher](https://github.com/goatcorp/FFXIVQuickLauncher) issue. Mistakes happen, thought it better to ask.

**Comment by Soreepeong** [comment]
I also think that you might want to make an issue there instead, since XivAlexander has nothing to do with logging in.
