### ISSUE TITLE
Regarding the recent post by yoshi p

### ISSUE THREAD

**Issue by TechPoi** [Soreepeong/XivAlexander#425]
Hello just want to ask before i uninstall is it possible for them to detect base xivalexander and be able to ban people for use of it , just wanted to bring this up incase as I'm not entire knowledgeable on the subject, or is it still safe to use as my ping really makes it hard to even play the game.

**Comment by Fprh5367** [comment]
No one here is from SE, how would we know? Just uninstall it and don't use it if you think there exists a risk.

**Comment by bm01** [comment]
His recent post doesn't show that there's any change in their policy. It also says they can't detect everything. Basically it's the same as before, don't advertise, don't stream yourself or show screenshots with third-party tools visible, don't use tools that send packets to the server in a way the client can't. However you could also get banned tomorrow because they decided so, but it has always been like that.

**Comment by Fmk47** [comment]
I think what the OP (and myself) is interested in is  how xiv affects packets: I'm guessing it doesnt change packet info but it does affect packet submission rate, would anyone with knowledge on the subject comment if this is technically "packet spoofing" (a term yoshi p used)
