### ISSUE TITLE
Xivalex possibly breaks ACT network after patch 6.15

### ISSUE THREAD

**Issue by YongeI6** [Soreepeong/XivAlexander#450]
I have been having issues after updating to 6.15, but my ACT no longer works due to network connection errors, this happened after I launched the game with xivalex. So far, my friends have no issues with ACT but just me. I'm wondering if this is related to xivalex with the patch's new opcode

**Comment by copycatditto** [comment]
XivAlex isn't working right now, and as far as I know neither is the main branch of FFXIV ACT Plugin. In any case, I downloaded the current beta version of FFXIV ACT Plugin and it appears to be parsing fine while I have XivAlex open (it only gives me logged errors).
Are you using the current beta of FFXIV ACT Plugin and getting these errors? If you are on the main version, it isn't working because of the changes that are also affecting XivAlex, not because of XivAlex itself.

**Comment by YongeI6** [comment]
> Are you using the current beta of FFXIV ACT Plugin and getting these errors? If you are on the main version, it isn't working because of the changes that are also affecting XivAlex, not because of XivAlex itself.

Hello there, thanks for your help. 

I am currently running the main version of ACT, thank you for point out the reason behind it. I will download the beta version of ACT and waiting for both of them to get updated.
