### ISSUE TITLE
Feels slower post 6.15

### ISSUE THREAD

**Issue by YourCoastie** [Soreepeong/XivAlexander#457]
I know they changed their code and it had to be updated but I can't triple weave, like at all now. Where as before 6.15 I could do it pretty easily. To note, I was and am using NoClippy alongside it, which I found to work tremendously well. Is there room for improvement still with the new code?

**Comment by YourCoastie** [comment]
> You're not supposed to be able to triple weave...
It's literally advertised. on the main page.

 _This add-on will make double (or triple, depending on your skill/spell speed) weaving always possible. No more low DPS output just because you are on high latency network._

**Comment by madara4567** [comment]
> You're not supposed to be able to triple weave...

So? I don't/can't triple weave with it but since SE has a zero tolerance policy with regard to third party apps, you will get banned no matter what if they had a way to detect you where using XivAlexander , wouldn't you?

So really you may as well triple weave even though it would give you an unfair advantage. There's a million apps I literally see active streamers using, that give them an unfair advantage. Like a slidecasting app for black mage. The rank 1 BLM is literally using atleast 4 apps, on screen, while streaming, until this day.
