### ISSUE TITLE
Error when trying to run program

### ISSUE THREAD

**Issue by PengBooz** [Soreepeong/XivAlexander#5]
How do I fix this error? Happens every time I try to load the program with ffxiv.

https://imgur.com/a/UcROaGj

**Comment by Soreepeong** [comment]
If you're using another addon (like addons in Dalamud from XIVLauncher), tell what else you're using. Also, run
> `cmd /c tasklist > %TEMP%\a.txt`

in Windows+R (Run dialog), and share the contents of `a.txt` inside `%TEMP%` which you can access from Run dialog again, because there might be something that does something conflicting with XivAlexander.

Please note that I might be unable to fix this by myself, in which case, sorry about that. You can always try the other solution we can't get this addon working at your PC. https://github.com/Soreepeong/XivMitmLatencyMitigator
