### ISSUE TITLE
6.2 Hotfix NA?

### ISSUE THREAD

**Issue by Cort69** [Soreepeong/XivAlexander#503]
Has anyone gotten it to work in NA since 6.2?

**Comment by ZeteCx** [comment]
> 

yeah sadly there are bunch of crashing issues and the devs went quiet for months now

**Comment by GavarKhai** [comment]
> > 
> 
> yeah sadly there are bunch of crashing issues and the devs went quiet for months now

pretty sure the last time he responded to anyone he tried to say an issue i and another user were having was because of failing drives. i proved him wrong by uninstalling XIVAlexander and FFXIV and re-installing on the same drive which was months ago and haven't had issues since. it was XIVAlexander corrupting the game files for some reason. he hasn't responded to any posts since then and that was months ago.

**Comment by ZeteCx** [comment]
> > > 
> > 
> > 
> > yeah sadly there are bunch of crashing issues and the devs went quiet for months now
> 
> pretty sure the last time he responded to anyone he tried to say an issue i and another user were having was because of failing drives. i proved him wrong by uninstalling XIVAlexander and FFXIV and re-installing on the same drive which was months ago and haven't had issues since. it was XIVAlexander corrupting the game files for some reason. he hasn't responded to any posts since then and that was months ago.
> 
> here's the link to said post - #460

Yeah.. i hope they are ok.

**Comment by retaker** [comment]
Please update to the latest opcodes and try again. Please open a new issue if the problem persists.
