### ISSUE TITLE
Icon missing in system tray on taskbar

### ISSUE THREAD

**Issue by DrobotTech** [Soreepeong/XivAlexander#585]
Today I noticed that the taskbar icon for alexander was missing even though it was hooked into the game and running fine. Since the icon is gone I can't open the control window to change any settings in alexander without deleting the config to make the control window appear again

**Comment by requiem2017** [comment]
Same issue, have to keep the "HideOnMinimize_XivAlexMainWindow" false

**Comment by hyskylord** [comment]
Any fix for this right now?

**Comment by jakob153** [comment]
I think i managed to fix it. The issue was adding NIF_GUID to the flags but no GUID was provided so it was trying to reference it.
Removing it takes the uID defined above. If @Soreepeong can give me access I can create a PR for this. In the meantime you can download this dll and replace it in your game directory. Make sure to make a copy before!
![Screenshot 2023-05-04 072817](https://user-images.githubusercontent.com/17678207/236119055-6b1143cc-3b29-4ee7-8617-231080e261d0.png)
[d3d11.zip](https://github.com/Soreepeong/XivAlexander/files/11393232/d3d11.zip)
