### ISSUE TITLE
VPN changing remote address

### ISSUE THREAD

**Issue by hyskylord** [Soreepeong/XivAlexander#8]
Some VPN will change remote address to 127.0.0.1, and game packet will be ignored, maybe it would be better to add 0x7F to netmask filter.

**Comment by LittleNightmare** [comment]
in addition, I'm not sure it works on cn server or not. it marks ignore to server IP either I use VPN or not. (but I can sure its opcode finder does not work on cn server.) I am stilling looking for RequestUseAction, it does not list in any table

**Comment by Soreepeong** [comment]
@hyskylord The IP limitation is actually a stopgap for the time being, because the program fails to process sockets that isn't conveying game traffic. This will be fixed when I get the netcode right.

@LittleNightmare Since I don't have access to Chinese datacenters, I do not know the IP addresses. I'll add to inclusion list if you can tell me Chinese datacenters' IP address range.

**Comment by Soreepeong** [comment]
https://github.com/Soreepeong/XivAlexander/releases/tag/v1.06

This release lets you edit IP range to intercept from configuration.
